package cmd

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/spf13/cobra"
)

func init() {
	rootCmd.AddCommand(removeCmd)
}

var removeCmd = &cobra.Command{
	Use:   "remove [name]",
	Short: "Remove an existing script",
	Long:  "Remove an existing script previously generated by calling `make`. The name of the script is the name of the file without the extension.",
	Args:  cobra.ExactArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		scriptName := strings.ReplaceAll(strings.ToLower(args[0]), " ", "-")
		scriptFileName := fmt.Sprintf("%s.sh", scriptName)

		scriptDir, err := makeScriptDir()
		if err != nil {
			return fmt.Errorf("failed to find script directory: %v", err)
		}

		scriptPath := filepath.Join(scriptDir, scriptFileName)
		if _, err := os.Stat(scriptPath); os.IsNotExist(err) {
			return fmt.Errorf("script '%s' does not exist", scriptFileName)
		}

		err = os.Remove(scriptPath)
		if err != nil {
			return fmt.Errorf("failed to remove script '%s': %v", scriptFileName, err)
		}

		fmt.Printf("Removed script '%s'\n", scriptFileName)

		return nil
	},
}
